### PR TITLE
fix two bugs

### LINKED ISSUE #269: Pagination Breaks After Edit
# Reproduction

- Vote and create argument
- Edit argument and save
- Click on any page in the pagination.

The pagination links go to `https://rfc.stitcher.io/livewire/message/argument-list?page=2`. Which obviously doesn't work.

Suspect this has something to do with the pagination being based on the `previous` request.

### LINKED ISSUE #280: The color of strong tags in dark mode is difficult to read
image

It looks like the strong tag uses the color variable `--tw-prose-bold`, which remains the same value (`#111827`) regardless of dark mode or light mode.

This is different than the text color variable `--color-font`, which changes between `#adbac7` and `#1f2937` depending on whether light mode or dark mode is active.

I suspect we need to change the value of `--tw-prose-bold` in dark mode.

### PR DESCRIPTION
**Pull request by MohammadAlhallaq**
This PR closes #269 and closes #280 
It also fixes the style of the recommended RFCs as they were not sharing the width evenly.

before:
Screenshot 2023-09-06 at 10 58 59 PM

after:
Screenshot 2023-09-06 at 10 59 21 PM

### CODE REVIEW

File: app/Http/Livewire/ArgumentList.php [hunk 1]
```diff
@@ -74,7 +74,9 @@ public function render(): View
 
         $query = $sortField->applySort($query);
 
-        $arguments = $query->paginate(15);
+        $arguments = $query
+            ->paginate(15)
+            ->setPath(action(RfcDetailController::class, $this->rfc));
```
Comment (SerhiiCho) [inline app/Http/Livewire/ArgumentList.php:79]: This is how you fixed it? I had no idea how to do it 🤔

**Review by SerhiiCho — APPROVED** [review]
👍👍👍 Can you add `closes #269` to the initial comment to auto-close the issue? Or your `fixes this bug will work? I'm not sure

File: app/Http/Livewire/ArgumentList.php (hunk 1 above)
Comment (MohammadAlhallaq) [reply app/Http/Livewire/ArgumentList.php:79]: Yeah, actually, it took me some time to understand what was going on. It turns out that we need to set the path if we are going to use a custom pagination component because it works fine with the default component.

https://laracasts.com/discuss/channels/laravel/error-in-paginator-link-caused-by-livewiremessageservices-allpage2
https://github.com/livewire/livewire/discussions/3079

File: tailwind.config.js [hunk 2]
```diff
@@ -32,6 +32,17 @@ export default {
 
     theme: {
         extend: {
+            typography: {
```
Comment (SerhiiCho) [inline tailwind.config.js:35]: You are overwriting prose classes with our adaptive font? Much better than creating a helper class like it was before

File: resources/css/app.css [hunk 3]
```diff
@@ -17,15 +17,3 @@ pre.shiki {
 pre.shiki code {
     @apply max-w-[200px] block;
 }
-
-.markdown-text {
```
Comment (SerhiiCho) [inline resources/css/app.css:21]: I didn't like this here anyways 🤣

**Review by SerhiiCho — APPROVED** [review]

File: tailwind.config.js (hunk 2 above)
Comment (MohammadAlhallaq) [reply tailwind.config.js:35]: yeah much cleaner, no need for the text-markdown anymore!

File: resources/css/app.css (hunk 3 above)
Comment (MohammadAlhallaq) [reply resources/css/app.css:21]: Me neither, but I just found out about it in the Tailwind documentation! 😂

**Comment by brendt** [comment]
👍
